server:
  port: 9096

spring:
  application:
    name: cloud-oauth2-center

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:9090/eureka                                      # 单机
      defaultZone: http://eureka01.com:9089/eureka/,http://eureka02.com:9090/eureka/  # 集群
  instance:
    instance-id: cloud-oauth2-center:9096                  #自定义服务名称
    prefer-ip-address: true
security:
  oauth2:
    client:
      additional-information:                       #访问路径可以显示 IP 地址
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**
  user:
    name: admin
    password: admin
info:
  app.name: $project.artifactId$
  company.name: www.mace.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

