server:
  port: 80

spring:
  aop:
    proxy-target-class: true                      #使用 CGLIB 来实现AOP false:使用的是标准Java的实现。
  application:
    name: cloud-consumer-dept-ribbon-hystrix-80
  cloud:
    loadbalancer:
      retry:
        enabled: true                             #重试机制开关,默认false

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:9090/eureka                                      # 单机
      defaultZone: http://eureka01.com:9089/eureka/,http://eureka02.com:9090/eureka/  # 集群
  instance:
    instance-id: cloud-consumer-dept-ribbon-hystrix-80      #自定义服务名称
    prefer-ip-address: true
security:
  oauth2:
    client:
      additional-information:                       #访问路径可以显示 IP 地址

info:
  app.name: cloud-consumer-dept-ribbon-hystrix-80
  company.name: www.mace.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

ribbon:
  eager-load:
    enabled: true                                   #开启Ribbon的饥饿加载模式
    clients: cloud-provider-dept                    #指定需要饥饿加载的服务名
#Ribbon 超时时间设置
#ribbon:
#  ConnectTimeout: 500                              #http建立socket超时时间,毫秒
#  ReadTimeout:  3000                               #http读取响应socket超时时间
